require('dotenv').config()
const mongoose = require('mongoose')
const Product  = require('../models/Product')

const products = [
  // ─── DIVINE IDOLS ───────────────────────────────────────────────
  {
    name: 'Radha Raman Standard Size MDF Puja Idol',
    description: 'Radhe Creations Vastu suggests that Radha Krishna idols create an atmosphere of love, devotion and peace. The Radha Krishna Wood (MDF) Statue is a powerful, charming and positive sight. If you are discomforted by stress and business problems, you can place a Lord Krishna and Radha Statue playing the flute at your home and office. It will bring in more stability and harmony.',
    price: 349,
    originalPrice: 499,
    category: 'divine-idols',
    colour: 'Black',
    material: 'Wood (MDF)',
    dimensions: '40L x 30W x 70H MM',
    weight: '200 Gm',
    featured: true,
    rating: 4.5,
    reviewCount: 128,
    stock: 45,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Radha+Raman+Idol'],
  },
  {
    name: 'Banke Bihari Standard Size MDF Home Decor Idol',
    description: 'Radhe Creations Vastu suggests that Bankey Bihari idols create an atmosphere of devotion and peace. The Bankey Bihari Wood (MDF) Statue is a powerful, charming and positive sight. If you are discomforted by stress and business problems, you can place a Lord Krishna and Bankey Bihari (Vrindavan) for Home Decoration Height 6 Inches Multicolour.',
    price: 299,
    originalPrice: 449,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'Wood (MDF)',
    dimensions: '40L x 30W x 120H MM',
    weight: '200 Gm',
    featured: true,
    rating: 4.7,
    reviewCount: 213,
    stock: 60,
    images: ['https://placehold.co/600x600/f9f3e7/b84d00?text=Banke+Bihari+Idol'],
  },
  {
    name: 'Shrinath Ji Wooden MDF Cutout',
    description: 'Celebrate tradition and spirituality with the Radhe Creations MDF Shrinathji wooden Cutouts, a beautifully crafted decorative piece perfect for enhancing your home, temple, or event space. Designed with intricate detailing and vibrant colors, this cutout brings divine energy to your celebrations and rituals.',
    price: 279,
    originalPrice: 399,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'MDF',
    dimensions: '20L x 5W MM',
    weight: '200 Gm',
    featured: true,
    rating: 4.6,
    reviewCount: 95,
    stock: 80,
    images: ['https://placehold.co/600x600/ffefd6/923d07?text=Shrinath+Ji'],
  },
  {
    name: 'Radha Ballabh Lal Ji MDF Cutout',
    description: 'Radhe Creations Vastu suggests that Shri Radha Ballabh Lal Ji create an atmosphere of devotion and peace. It is believed that the Shri Radha Ballabh Lal Ji Wood (MDF) Statue is a powerful, charming and positive sight.',
    price: 320,
    originalPrice: 450,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'MDF',
    dimensions: '20D x 7W x 8H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.4,
    reviewCount: 67,
    stock: 35,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Radha+Ballabh'],
  },
  {
    name: 'Radha Rani Idol for Home Decor (Radhe Radhe)',
    description: 'Radhe Creations Vastu suggests that Radha Radha idols create an atmosphere of devotion and peace. The Bankey Bihari Wood (MDF) Statue is a powerful, charming and positive sight. You can place a Lord Krishna and Radha Radha for Home Decoration Height 6 Inches Multicolour.',
    price: 259,
    originalPrice: 379,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'MDF',
    dimensions: '20L x 7W x 8H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.3,
    reviewCount: 44,
    stock: 50,
    images: ['https://placehold.co/600x600/ffefd6/b84d00?text=Radha+Rani+Idol'],
  },
  {
    name: 'Baal Krishna Okhla Leela MDF Idol',
    description: 'Handcrafted with intricate detailing, this statue captures the essence of the beloved Hindu deity, known for his mischievous charm and profound wisdom. Measuring approximately 6 inches in height, this small figurine is a stunning centrepiece for your home temple or living space. The rich, warm tones of the wood lend an earthy and natural elegance.',
    price: 289,
    originalPrice: 399,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'MDF',
    dimensions: '20D x 7W x 8H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 82,
    stock: 40,
    images: ['https://placehold.co/600x600/f9f3e7/923d07?text=Baal+Krishna'],
  },
  {
    name: 'Vasudeva Carrying Baby Krishna MDF Idol',
    description: 'This Religious / Vastu Idol is Made of MDF Wooden Cutout with Durable & Long Lasting Colours in Marble Look. It is easily cleanable by Dry Cotton Cloth. This Decorative Murti can be used as Pooja Mandir Interior Decoration Accessories / Table Decor Items or Showcase Decoration.',
    price: 349,
    originalPrice: 499,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'MDF',
    dimensions: '20D x 7W x 8H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.6,
    reviewCount: 56,
    stock: 30,
    images: ['https://placehold.co/600x600/ffefd6/c9860a?text=Vasudeva+Krishna'],
  },
  {
    name: 'Bal Lilas of Kanha in Mathura Jail',
    description: 'Experience the divine presence of Lord Krishna in your home with this exquisite wooden figurine. Handcrafted with intricate detailing, this statue captures the essence of the beloved Hindu deity, known for his mischievous charm and profound wisdom. Measuring approximately 4 inches in height.',
    price: 379,
    originalPrice: 549,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'Wooden',
    dimensions: '20D x 7W x 8H CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.8,
    reviewCount: 102,
    stock: 25,
    images: ['https://placehold.co/600x600/f9f3e7/b84d00?text=Kanha+Mathura+Jail'],
  },
  {
    name: 'Radha Krishna Jhula – Wooden MDF Idol',
    description: 'Radhe Creations Radha Krishna is the Lord of Good Fortune who provides prosperity, fortune and success. Ideal product for Mandir murti, showpieces for home Decor, gifting, showpiece for living Room, showpieces, housewarming, inauguration, god idol for gift, Diwali gift, wedding anniversary gift.',
    price: 399,
    originalPrice: 599,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'Wooden',
    dimensions: '20D x 7W x 8H CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.9,
    reviewCount: 175,
    stock: 20,
    images: ['https://placehold.co/600x600/ffefd6/923d07?text=Radha+Krishna+Jhula'],
  },
  {
    name: 'Premanand Ji Maharaj Wall Hanging',
    description: 'Premium Premanand Ji Maharaj Wall Hanging for Living Room | Bedroom | Gifts | Decor Hanging | Spiritual Decoration, MDF Wooden. High Quality UV Print Crafted with advanced UV printing technology, each detail on this artwork is brought to life with vibrant, long-lasting colors.',
    price: 449,
    originalPrice: 649,
    category: 'divine-idols',
    colour: 'Multicolour',
    material: 'MDF',
    dimensions: '31L x 0.5W x 71H CM',
    weight: '330 Gm',
    featured: false,
    rating: 4.7,
    reviewCount: 88,
    stock: 35,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Premanand+Ji+Wall+Hang'],
  },

  // ─── FESTIVE SETS ────────────────────────────────────────────────
  {
    name: 'Lord Krishna with 8 Ashta Sakhi Idols',
    description: 'This decorative set features 8 Ashta Sakhi figurines, the beloved companions of Radha, symbolizing their devotion and assistance in her divine love for Krishna. Perfectly suited for Radha Krishna temples, this creation is ideal for Janmashtami celebrations, enhancing the spiritual essence of the occasion.',
    price: 599,
    originalPrice: 849,
    category: 'festive-sets',
    colour: 'Multicolour',
    material: 'Wood',
    dimensions: '20D x 7W x 5H MM',
    weight: '200 Gm',
    featured: true,
    rating: 4.8,
    reviewCount: 143,
    stock: 30,
    images: ['https://placehold.co/600x600/f9f3e7/b84d00?text=8+Ashta+Sakhi'],
  },
  {
    name: 'Makhan Chor Leela Set',
    description: 'The Shreeji Shyama Creations Kanha Ji Temple Decor is a beautifully crafted 3D wooden tabletop set designed to celebrate the essence of Janmashtami. This special decoration features scenes of Lord Krishna\'s iconic Makhan Chor Leela and Haran Leela, capturing his playful and divine moments.',
    price: 549,
    originalPrice: 799,
    category: 'festive-sets',
    colour: 'Multicolour',
    material: 'Wooden',
    dimensions: '10 x 5 x 2 CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.7,
    reviewCount: 119,
    stock: 40,
    images: ['https://placehold.co/600x600/ffefd6/923d07?text=Makhan+Chor+Leela'],
  },
  {
    name: 'Rass Leela Set Wooden MDF Idol',
    description: 'The Ashta Sakhi Idol Statue Showpiece is a beautifully crafted decorative piece designed for enhancing the aesthetic appeal of your home. It features intricately carved representations of the Ashta Sakhi, the eight principal companions of Radha who assisted her in her divine love for Krishna.',
    price: 499,
    originalPrice: 699,
    category: 'festive-sets',
    colour: 'Multicolour',
    material: 'Wooden',
    dimensions: '10L x 7W x 5H CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.6,
    reviewCount: 87,
    stock: 35,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Rass+Leela+Set'],
  },
  {
    name: 'Holi Gopi Set Wooden MDF Cut Out',
    description: 'This beautifully crafted wooden cutout set features Lord Krishna, Radha, and the Gopis, capturing the spirit of Holi – the festival of love, joy, and devotion. Handcrafted with precision and adorned with vibrant detailing, this Holi Special Set brings the essence of Vrindavan\'s Rasleela into your home.',
    price: 429,
    originalPrice: 599,
    category: 'festive-sets',
    colour: 'Multicolor',
    material: 'Wooden',
    dimensions: '4.3 CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 64,
    stock: 45,
    images: ['https://placehold.co/600x600/ffefd6/b84d00?text=Holi+Gopi+Set'],
  },
  {
    name: 'Dhai Handi Ladu Gopal – Janmashtami Decoration Toy',
    description: 'This accessory is crafted from durable plastic, symbolizing the traditional "Dhai Handi" associated with Lord Krishna\'s playful antics. Ideal for enhancing the festive ambiance, it pairs beautifully with Ladu Gopal idols and other Mandir accessories, adding a touch of cultural charm and vibrant decor to your celebrations.',
    price: 199,
    originalPrice: 299,
    category: 'festive-sets',
    colour: 'Brown',
    material: 'Plastic-Glossy',
    dimensions: '2 CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.3,
    reviewCount: 52,
    stock: 100,
    images: ['https://placehold.co/600x600/f9f3e7/923d07?text=Dhai+Handi'],
  },
  {
    name: 'Nav Durga Wooden MDF (Set of 9 Pcs)',
    description: 'Nav Durga Wooden Handmade Decorated Multi Color set is specially designed for Navratri festival. This Decorative is made by MDF wooden handmade handicraft and hand painted. This attractive piece is perfect to decorate during the festival and could also be used for worship. The nine forms of Durga are often considered collectively as a single deity.',
    price: 649,
    originalPrice: 899,
    category: 'festive-sets',
    colour: 'Multicolour',
    material: 'MDF',
    dimensions: '20L x 7W x 8H CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.8,
    reviewCount: 134,
    stock: 25,
    images: ['https://placehold.co/600x600/ffefd6/c9860a?text=Nav+Durga+Set'],
  },
  {
    name: 'Aashta Sakha Wooden MDF (Set of 8 Pcs)',
    description: 'This decorative set features 8 Ashta Sakha figurines, the beloved companions of Radha, symbolizing their devotion and assistance in her divine love for Krishna. Perfectly suited for Radha Krishna temples, this creation is ideal for Janmashtami celebrations, enhancing the spiritual essence of the occasion.',
    price: 579,
    originalPrice: 799,
    category: 'festive-sets',
    colour: 'Multicolor',
    material: 'MDF',
    dimensions: '20L x 7W x 5H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.6,
    reviewCount: 71,
    stock: 30,
    images: ['https://placehold.co/600x600/f9f3e7/b84d00?text=Aashta+Sakha+Set'],
  },
  {
    name: 'Govardhan Parvat Jhaki Leela Set',
    description: 'Govardhan Parvat Jhaki Wooden Handmade Decorated Multi Color Lord Krishna/Laddu Gopal is specially designed for Bal Gopal festival Krishna Janmashtami. This attractive piece is perfect to decorate during the festival and could also be used for worship. This is perfect standard size which you can place at your car dashboard, worship place, office desk.',
    price: 489,
    originalPrice: 699,
    category: 'festive-sets',
    colour: 'Multicolour',
    material: 'MDF',
    dimensions: '20D x 7W x 8H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 58,
    stock: 40,
    images: ['https://placehold.co/600x600/ffefd6/923d07?text=Govardhan+Parvat'],
  },
  {
    name: 'Ganesh Ji Band Wooden MDF Cutout (Set of 9 Pcs)',
    description: 'Ganesh Ji Band (MDF) Statue is a powerful, charming and positive sight. If you are discomforted by stress and business problems, you can place a Ganesh Ji Band wooden MDF idol for Home Decoration Height 6 Inches Multicolour.',
    price: 699,
    originalPrice: 999,
    category: 'festive-sets',
    colour: 'Multicolour',
    material: 'Wooden',
    dimensions: '10L x 20W x 12H CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.7,
    reviewCount: 96,
    stock: 20,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Ganesh+Ji+Band'],
  },
  {
    name: 'Bal Krishna Fridge Magnet for Decoration (Set of 5 Pcs)',
    description: 'Radhe Creations Set of 5 Pcs Stunning 3D Effects. Witness the divine transformation as the image shifts and moves, bringing Lord Krishna Lalla to life with depth and vibrance. High-Quality & Durable Build Crafted from superior materials, this magnet is built to last, retaining its vibrant colors and stunning 3D effect over time.',
    price: 149,
    originalPrice: 249,
    category: 'festive-sets',
    colour: 'Multicolor',
    material: 'Magnet',
    dimensions: 'Oval',
    weight: '200 Gm',
    featured: false,
    rating: 4.4,
    reviewCount: 203,
    stock: 150,
    images: ['https://placehold.co/600x600/ffefd6/b84d00?text=Bal+Krishna+Magnet'],
  },
  {
    name: 'Radhe Radhe Wall Stickers with Lord Krishna & Radha (3 Pcs)',
    description: 'This Radhe Radhe is Beautifully Handcrafted sticker image with Krishna And Radha In Sequence. Decorate Your Door, Walls, Floor, Table, Entrance, Pooja Room, Etc With This On Festivals & Occasions. It\'s One Of The Best Gifting Corporate Gift, Kitty Party, House Warming Party, Diwali, Rakhi, Makar Sankranti, Pongal, Lohri & Other Festivals.',
    price: 99,
    originalPrice: 179,
    category: 'festive-sets',
    colour: 'Multicolour',
    material: 'Sticker',
    dimensions: '2 CM',
    weight: '90 Gm',
    featured: false,
    rating: 4.2,
    reviewCount: 312,
    stock: 200,
    images: ['https://placehold.co/600x600/f9f3e7/923d07?text=Radhe+Radhe+Stickers'],
  },

  // ─── HOME DÉCOR ──────────────────────────────────────────────────
  {
    name: 'Kamdhenu Cow and Calf Idol – Metal Gold Finish',
    description: 'This intricately designed idol adheres to Vastu principles, making it an ideal addition to your home or office for promoting positive energy and well-being. Metal Craftsmanship: Crafted from high-quality metal, the sculpture showcases meticulous craftsmanship, capturing the grace and beauty of Kamdhenu and her calf.',
    price: 799,
    originalPrice: 1199,
    category: 'home-decor',
    colour: 'Gold Finish',
    material: 'Metal',
    dimensions: '12L x 12W x 6H CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.8,
    reviewCount: 156,
    stock: 30,
    images: ['https://placehold.co/600x600/ffefd6/c9860a?text=Kamdhenu+Metal+Gold'],
  },
  {
    name: 'Kamdhenu Cow and Calf Idol – Fiber Finish',
    description: 'Radhe Creations The Kamdhenu Cow with Calf holds immense spiritual significance, symbolizing motherhood, nourishment, and the divine blessings of Gau MATA. Vastu Compliant: This intricately designed idol adheres to Vastu principles, making it an ideal addition to your home or office for promoting positive energy and well-being.',
    price: 649,
    originalPrice: 999,
    category: 'home-decor',
    colour: 'Multicolour',
    material: 'Fiber',
    dimensions: '12D x 12W x 6H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.6,
    reviewCount: 89,
    stock: 25,
    images: ['https://placehold.co/600x600/f9f3e7/b84d00?text=Kamdhenu+Fiber'],
  },
  {
    name: 'Animal Toy – Metallic Meena Work (Set of 12)',
    description: 'This set, which includes iconic animals like the peacock, elephant, and more, is perfect for adding a touch of traditional artistry and vibrant color to your décor or collection. The Shreeji Shyama Creations Animal Toy Set of 12 with Metallic Meena Work is a celebration of heritage and craftsmanship.',
    price: 549,
    originalPrice: 799,
    category: 'home-decor',
    colour: 'Multicolour',
    material: 'Metal',
    dimensions: '19L x 2W x 18H CM',
    weight: '100 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 74,
    stock: 40,
    images: ['https://placehold.co/600x600/ffefd6/923d07?text=Animal+Meena+Work'],
  },
  {
    name: 'Ganesh & Laxmi Ji MDF Wooden Cutout',
    description: 'Crafted from high-quality MDF wood, it features detailed cutouts of Lord Ganesh and Goddess Laxmi, symbolizing prosperity and good fortune. This multipurpose product can be used for toran making, wall hangings, or as part of a DIY rangoli kit, making it perfect for Diwali, Dusshera, weddings, poojas, and other festive occasions.',
    price: 349,
    originalPrice: 499,
    category: 'home-decor',
    colour: 'Multicolor',
    material: 'MDF',
    dimensions: '20L x 7W CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.7,
    reviewCount: 183,
    stock: 60,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Ganesh+Laxmi+Cutout'],
  },
  {
    name: 'Golden Multicolor Amboz Fiber Dancing Peacock',
    description: 'This Paper Mache decorative item Enhances the decor value of the house, office, hotel, temple, etc. Great ideas for wedding gifts, anniversary gifts, house warming ceremonies, Birthday gifts, new ventures, award ceremonies, Diwali, and festival gifts. A valuable personal collectible collection.',
    price: 499,
    originalPrice: 749,
    category: 'home-decor',
    colour: 'Multicolour',
    material: 'Fiber',
    dimensions: '12L x 12W x 6H CM',
    weight: '200 Gm',
    featured: true,
    rating: 4.6,
    reviewCount: 127,
    stock: 35,
    images: ['https://placehold.co/600x600/ffefd6/b84d00?text=Dancing+Peacock+Fiber'],
  },
  {
    name: 'Golden Multicolor Amboz Metal Dancing Peacock (Set of 2)',
    description: 'This Paper Mache decorative item Enhances the decor value of the house, office, hotel, temple, etc. Great ideas for wedding gifts, anniversary gifts, house warming ceremonies, Birthday gifts, new ventures, award ceremonies, Diwali, and festival gifts. A valuable personal collectible collection.',
    price: 699,
    originalPrice: 999,
    category: 'home-decor',
    colour: 'Multicolour',
    material: 'Metal',
    dimensions: '12L x 12W x 6H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.7,
    reviewCount: 91,
    stock: 20,
    images: ['https://placehold.co/600x600/f9f3e7/923d07?text=Metal+Peacock+Set'],
  },
  {
    name: 'Elephants Pair Fiber Statue Designer Showpiece (Set of 2)',
    description: 'Adorned with colorful detailing, this elegant pair of elephants enhances the charm of any space, making it perfect for home décor, office embellishment, and pooja settings. The Shreeji Shyama Creations Decorative Elephants Pair Fiber Statue is more than just a showpiece—it\'s a blend of artistry and tradition, bringing elegance and positivity to any space.',
    price: 449,
    originalPrice: 649,
    category: 'home-decor',
    colour: 'Multicolour',
    material: 'Fiber',
    dimensions: '10L x 4W x 7.5H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 68,
    stock: 30,
    images: ['https://placehold.co/600x600/ffefd6/c9860a?text=Elephant+Pair+Fiber'],
  },
  {
    name: 'Pooja Thali – Roli Chawal Platter',
    description: 'Pooja Thali made from high-quality metal, this thali is sturdy, durable, and easy to maintain. The smooth finish and vibrant enamel work ensure it retains its beauty and remains rust-free for long-term use.',
    price: 299,
    originalPrice: 449,
    category: 'home-decor',
    colour: 'Multicolour',
    material: 'Metal',
    dimensions: '25L x 2W x 25H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.4,
    reviewCount: 142,
    stock: 50,
    images: ['https://placehold.co/600x600/f9f3e7/b84d00?text=Pooja+Thali'],
  },
  {
    name: 'Haldi Mehndi Shaadi Readymade Rangoli Mat',
    description: 'The Radhe Creations Haldi Mehndi Shaadi Readymade Rangoli Mat is an elegant and versatile decorative item designed to enhance the beauty of your celebrations and spaces. This rangoli mat is perfect for Haldi and Mehndi ceremonies, weddings, and Diwali decorations, bringing a touch of traditional charm to any occasion.',
    price: 249,
    originalPrice: 399,
    category: 'home-decor',
    colour: 'Multicolor',
    material: 'Metal',
    dimensions: '20L x 20W x 1H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.3,
    reviewCount: 88,
    stock: 45,
    images: ['https://placehold.co/600x600/ffefd6/923d07?text=Rangoli+Mat'],
  },
  {
    name: 'Mataki Set for Laddu Gopal (Set of 3 Pcs)',
    description: 'Radhe Creations Designer Wooden Handcrafted Matki Set for Laddu Gopal, Kanha Ji. Lets celebrate this Janmashtami with Dahi Handi, Matka for Laddu Gopal. Get Laddu Gopal dahi handi, Kanha Ji Matki at best price. Colors are according to availability.',
    price: 229,
    originalPrice: 349,
    category: 'home-decor',
    colour: 'Orange',
    material: 'Wooden',
    dimensions: '20L x 7W x 8H CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.4,
    reviewCount: 116,
    stock: 70,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Mataki+Set'],
  },

  // ─── KIDS & TOYS ─────────────────────────────────────────────────
  {
    name: 'Tir Tir Rattles for Babies',
    description: 'Introduce your child to the world of rhythm, sound, and sensory exploration with this beautifully handcrafted Wooden Musical Toy Set. Each piece is made from high-quality, non-toxic wood and painted with eco-friendly colors, ensuring a safe and durable play experience for toddlers and preschoolers.',
    price: 149,
    originalPrice: 249,
    category: 'kids-toys',
    colour: 'Yellow',
    material: 'Wooden',
    dimensions: 'Standard',
    weight: '150 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 234,
    stock: 100,
    images: ['https://placehold.co/600x600/ffefd6/b84d00?text=Tir+Tir+Rattle'],
  },
  {
    name: 'Pinjhara Rattles for Babies',
    description: 'Introduce your child to the world of rhythm, sound, and sensory exploration with this beautifully handcrafted Wooden Musical Toy Set. Each piece is made from high-quality, non-toxic wood and painted with eco-friendly colors, ensuring a safe and durable play experience for toddlers and preschoolers.',
    price: 149,
    originalPrice: 249,
    category: 'kids-toys',
    colour: 'Blue',
    material: 'Wooden',
    dimensions: 'Standard',
    weight: '150 Gm',
    featured: false,
    rating: 4.4,
    reviewCount: 189,
    stock: 100,
    images: ['https://placehold.co/600x600/f9f3e7/923d07?text=Pinjhara+Rattle'],
  },
  {
    name: 'Hilna Rattles for Babies',
    description: 'Introduce your child to the world of rhythm, sound, and sensory exploration with this beautifully handcrafted Wooden Musical Toy Set. Each piece is made from high-quality, non-toxic wood and painted with eco-friendly colors, ensuring a safe and durable play experience for toddlers and preschoolers.',
    price: 149,
    originalPrice: 249,
    category: 'kids-toys',
    colour: 'White',
    material: 'Wooden',
    dimensions: 'Standard',
    weight: '150 Gm',
    featured: false,
    rating: 4.3,
    reviewCount: 156,
    stock: 100,
    images: ['https://placehold.co/600x600/ffefd6/c9860a?text=Hilna+Rattle'],
  },
  {
    name: 'Ball Jhan Jhan Rattles for Babies',
    description: 'Introduce your child to the world of rhythm, sound, and sensory exploration with this beautifully handcrafted Wooden Musical Toy Set. Each piece is made from high-quality, non-toxic wood and painted with eco-friendly colors, ensuring a safe and durable play experience for toddlers and preschoolers.',
    price: 179,
    originalPrice: 279,
    category: 'kids-toys',
    colour: 'Multicolour',
    material: 'Wooden & Rubber',
    dimensions: 'Standard',
    weight: '150 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 198,
    stock: 80,
    images: ['https://placehold.co/600x600/f9f3e7/b84d00?text=Ball+Jhan+Jhan'],
  },
  {
    name: 'Jhan Jhan Rattles for Babies',
    description: 'Introduce your child to the world of rhythm, sound, and sensory exploration with this beautifully handcrafted Wooden Musical Toy Set. Each piece is made from high-quality, non-toxic wood and painted with eco-friendly colors, ensuring a safe and durable play experience for toddlers and preschoolers.',
    price: 169,
    originalPrice: 269,
    category: 'kids-toys',
    colour: 'Multicolour',
    material: 'Wooden & Steel',
    dimensions: 'Standard',
    weight: '150 Gm',
    featured: false,
    rating: 4.4,
    reviewCount: 167,
    stock: 80,
    images: ['https://placehold.co/600x600/ffefd6/923d07?text=Jhan+Jhan+Rattle'],
  },
  {
    name: 'Tic Tac Toe Wood Board Game',
    description: 'Tic Tac Toe Board Game, XOXO Wooden block with Zero And Cross Game timepass and Mind Strategy toy, Non-toxic learning toy, noughts and crosses game for Kids and Adults, Multicolor. Bring the timeless joy of Tic Tac Toe to life with this robust indoor outdoor garden game set.',
    price: 249,
    originalPrice: 399,
    category: 'kids-toys',
    colour: 'Multi Color',
    material: 'Wooden',
    dimensions: '10L x 10W CM',
    weight: '300 Gm',
    featured: true,
    rating: 4.6,
    reviewCount: 287,
    stock: 60,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Tic+Tac+Toe'],
  },
  {
    name: 'Dum Dum Wooden Toy Car',
    description: 'The Radhe Creations Dum Dum Toy Car is a fun and engaging toy designed to entertain and delight young children. Its vibrant colors, smooth design, and durable build make it a perfect choice for toddlers and babies to enjoy endless hours of play. Made from high-quality, non-toxic, and lightweight materials, making it safe for children to play with.',
    price: 199,
    originalPrice: 329,
    category: 'kids-toys',
    colour: 'Multicolour',
    material: 'Wooden',
    dimensions: '14 x 12 x 12.5 CM',
    weight: '250 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 142,
    stock: 50,
    images: ['https://placehold.co/600x600/ffefd6/b84d00?text=Dum+Dum+Toy+Car'],
  },
  {
    name: 'Smiley Stacking Colorful 5 Teddy Rings',
    description: 'This educational plaything features colourful plastic rings in a delightful penguin shape, stacked atop a sturdy base. Designed for little hands aged 1 year and above, it encourages early learning through sorting, stacking, and colour recognition. The bright hues captivate young minds and aid in developing colour awareness.',
    price: 179,
    originalPrice: 299,
    category: 'kids-toys',
    colour: 'Multicolor',
    material: 'Plastic',
    dimensions: '25 x 20 x 20 CM',
    weight: '200 Gm',
    featured: false,
    rating: 4.4,
    reviewCount: 198,
    stock: 75,
    images: ['https://placehold.co/600x600/f9f3e7/923d07?text=Teddy+Stacking+Rings'],
  },
  {
    name: 'BPA Free Plastic Rattles (Set of 4)',
    description: 'This vibrant set includes four uniquely shaped ABS-plastic rattles, designed to captivate little ones with engaging sounds and vivid colors. Crafted from non-toxic, baby-safe material, each rattle has easy-grasp handles perfect for tiny hands, supporting early motor skill development.',
    price: 199,
    originalPrice: 349,
    category: 'kids-toys',
    colour: 'Multicolour',
    material: 'Plastic',
    dimensions: 'Standard',
    weight: '150 Gm',
    featured: false,
    rating: 4.3,
    reviewCount: 223,
    stock: 90,
    images: ['https://placehold.co/600x600/ffefd6/c9860a?text=BPA+Free+Rattles'],
  },
  {
    name: 'Wooden Designer Pencil for Kids (Set of 5 Pcs)',
    description: 'Add a touch of fun and creativity to your writing and drawing with the Lakshya India Wooden Pencil Set. This set includes 5 pencils, each featuring a unique and cute animal or bird face. Perfect for making schoolwork and homework more enjoyable, these pencils spark imagination and encourage creativity.',
    price: 129,
    originalPrice: 199,
    category: 'kids-toys',
    colour: 'Multicolour',
    material: 'Wooden',
    dimensions: '2L x 2W x 20H CM',
    weight: '60 Gm',
    featured: false,
    rating: 4.4,
    reviewCount: 312,
    stock: 150,
    images: ['https://placehold.co/600x600/f9f3e7/b84d00?text=Designer+Pencils'],
  },
  {
    name: 'Realistic Sliceable 7 Pcs Fruits Cutting Play Toy',
    description: 'Radhe Creations Cutting toy food comes with velcro that makes cutting sound, easy to attract your little kids attention, entertains and builds skills for toddler! All pieces are easy to store in the Bag, keeps your house clean and cultivates kids storage habit since childhood! BPA-free & 100%-safe, thick & durable, washable & unfading.',
    price: 249,
    originalPrice: 399,
    category: 'kids-toys',
    colour: 'Multicolour',
    material: 'Plastic',
    dimensions: 'Standard',
    weight: '300 Gm',
    featured: true,
    rating: 4.6,
    reviewCount: 267,
    stock: 65,
    images: ['https://placehold.co/600x600/ffefd6/923d07?text=Fruits+Cutting+Toy'],
  },
  {
    name: 'Xylophone Musical Instrument for Kids',
    description: 'The Shreeji Shyama Creations Xylophone is more than just a toy—it\'s a joyful learning tool that combines fun, music, and development, making it a must-have for every little musician. Produces clear and pleasant sounds, introducing children to the basics of melody and rhythm. Made from non-toxic, high-quality materials with smooth edges for safe play.',
    price: 299,
    originalPrice: 449,
    category: 'kids-toys',
    colour: 'Multicolour',
    material: 'Wooden & Metal',
    dimensions: '11 x 1 x 22 CM',
    weight: '100 Gm',
    featured: true,
    rating: 4.7,
    reviewCount: 178,
    stock: 55,
    images: ['https://placehold.co/600x600/f9f3e7/c9860a?text=Xylophone'],
  },
  {
    name: '36 Pieces Mini Puzzle Foam ABC Mat for Kids',
    description: 'Baby Foam Play Mat (36-Piece Set) 4x4 Inches Interlocking Alphabet and Numbers Floor Puzzle Colorful EVA Tiles, Girls, Boys Soft, Reusable, Easy to Clean. Great for your home, classroom, or even daycare. Features brightly colored letters and numbers that connect on the floor to create a fun play area!',
    price: 349,
    originalPrice: 549,
    category: 'kids-toys',
    colour: 'Multicolour',
    material: 'Rubber',
    dimensions: '31L x 31W CM',
    weight: '300 Gm',
    featured: false,
    rating: 4.5,
    reviewCount: 201,
    stock: 45,
    images: ['https://placehold.co/600x600/ffefd6/b84d00?text=Foam+ABC+Mat'],
  },
]


async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log('Connected to MongoDB')

    // Drop indexes to avoid slug conflicts from old data
    try {
      await Product.collection.dropIndexes()
      console.log('Dropped old indexes')
    } catch (e) {}

    await Product.deleteMany({})
    console.log('Cleared existing products')

    // Add unique slug to every product (insertMany bypasses pre-save hooks)
    const productsWithSlugs = products.map((p, i) => ({
      ...p,
      slug: p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') + '-' + (i + 1)
    }))

    const inserted = await Product.insertMany(productsWithSlugs)
    console.log('Successfully seeded ' + inserted.length + ' products!')
    console.log('\nProduct breakdown:')
    const cats = ['divine-idols', 'festive-sets', 'home-decor', 'kids-toys']
    for (const cat of cats) {
      const count = inserted.filter(p => p.category === cat).length
      console.log('   ' + cat + ': ' + count + ' products')
    }
    mongoose.connection.close()
    console.log('\nDone! Run: npm run dev to start the server.')
  } catch (err) {
    console.error('Seed error:', err.message)
    process.exit(1)
  }
}

seed()
